# Travis CI config for Laniakea Spark
language: python
dist: trusty

python:
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
 - pip install flake8
 - pip install -r requirements.txt

script:
  - ./setup.py build
  - ./setup.py install --root=/tmp
  # E722 should not actually be ignored...
  - flake8 --ignore E501,E303,E261,E302,E221,E722 spark/
