# Travis CI config for Laniakea Spark
language: python
dist: bionic

python:
  - "3.7"
  - "3.8"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
 - pip install flake8
 - pip install -r requirements.txt

script:
  - ./setup.py build
  - ./setup.py install --root=/tmp
  - flake8 spark/
